spring:
  profiles:
    active:
      - dev

---
spring:
  profiles:
    active: dev
  application:
    name: config-dev
    
---

spring:
  profiles:
    active: test
  application:
    name: config-test
    
#以UTF-8形式保存