spring:
  application:
    name: cloud-dept
  profiles:
    active: dev

---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: cloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb01
    username: root
    password: 1234

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.xkt.entity
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com/eureka
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true

info:
  app.name: cloud-config20
  company.name: www.xkt.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$


---

server:
  port: 8001
spring:
  profiles: test
  application:
    name: cloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb02
    username: root
    password: 1234

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.xkt.entity
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com/eureka
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true

info:
  app.name: cloud-config20
  company.name: www.xkt.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
